import os
from typing import TYPE_CHECKING

from nomad.datamodel.data import ArchiveSection, EntryData
from nomad.datamodel.metainfo.annotations import (
    BrowserAdaptors,
    BrowserAnnotation,
    ELNAnnotation,
    ELNComponentEnum,
)
from nomad.datamodel.metainfo.basesections import Measurement, MeasurementResult
from nomad.metainfo.metainfo import Quantity, SchemaPackage, Section, SubSection

from nomad_plugin_tutorials.parsers.reader import read_data_file
from nomad_plugin_tutorials.parsers.utils import merge_sections

if TYPE_CHECKING:
    from nomad.datamodel.datamodel import EntryArchive
    from structlog.stdlib import BoundLogger

m_package = SchemaPackage()


class OpticalMicroscopySettings(ArchiveSection):
    resolution = Quantity(
        type=int,
        description='Resolution of the resulting image in terms of pixels.',
        shape=[2],
        a_eln=ELNAnnotation(component=ELNComponentEnum.NumberEditQuantity),
    )
    magnification = Quantity(
        type=float,
        description='Magnification factor used for the resulting image.',
        a_eln=ELNAnnotation(component=ELNComponentEnum.NumberEditQuantity),
    )


class OpticalMicroscopyResults(MeasurementResult):
    image = Quantity(
        type=str,
        description='Image file generated by the microscope.',
        a_eln=ELNAnnotation(component=ELNComponentEnum.FileEditQuantity),
        a_browser=BrowserAnnotation(adaptor=BrowserAdaptors.RawFileAdaptor),
    )


class OpticalMicroscopy(Measurement, EntryData):
    """
    An example ELN schema for optical microscopy measurements. Using `EntryData` as
    a parent section enables this section to be used for creating NOMAD entries.
    """

    m_def = Section(
        label='Optical Microscopy (Parser Tutorial 2)',
    )
    data_file = Quantity(
        type=str,
        description='Data file coming from the microscope.',
        a_eln=ELNAnnotation(component=ELNComponentEnum.FileEditQuantity),
        a_browser=BrowserAnnotation(adaptor=BrowserAdaptors.RawFileAdaptor),
    )
    settings = SubSection(section_def=OpticalMicroscopySettings)
    results = SubSection(section_def=OpticalMicroscopyResults, repeats=True)

    def write_data(self, data_dict: dict, logger: 'BoundLogger') -> None:
        """
        Writes the data from the provided dictionary to the quantities of the schema.
        Uses the `merge_sections` utility function to merge the data coming from data
        file and that coming from the user's interaction with ELN quantities.

        Args:
            data_dict (dict): A dictionary containing the data to be written.
            logger (BoundLogger): A structlog logger.
        """
        measurement = OpticalMicroscopy()

        ## Tutorial 2.3 and 2.4 ##
        # Implement the writing logic
        # First populate `measurement` with the data from the `data_dict`
        # and then merge it into the entry archive
        # Hints:
        # - Significant part of the code from the tutorial 1 parser can be reused here
        # - Use the `merge_sections` utility function from `utils.py`

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        """
        Redefining the `normalize` method to read the data from the provided file and
        populate other quantities of the schema. This method is called when the entry
        is processed.
        """

        super().normalize(archive, logger)

        data_dict = {}
        ## Tutorial 2.2 ##
        # Read the metadata into data_dict and use it to populate the quantities
        # of the schema
        # Hints:
        # - Use the `read_data_file` utility function from `reader.py`
        # - Note that the process should only start if `data_file` has been added
        # to the ELN. By default, not populated quantities are set to `None`
        raise NotImplementedError


m_package.__init_metainfo__()
