import os
from typing import TYPE_CHECKING

from nomad.datamodel.data import ArchiveSection
from nomad.datamodel.metainfo.annotations import (
    BrowserAdaptors,
    BrowserAnnotation,
    ELNAnnotation,
    ELNComponentEnum,
)
from nomad.datamodel.metainfo.basesections import Measurement, MeasurementResult
from nomad.datamodel.metainfo.eln import ElnParserSection
from nomad.metainfo.metainfo import Quantity, SchemaPackage, Section, SubSection

from nomad_plugin_tutorials.parsers.reader import read_data_file
from nomad_plugin_tutorials.parsers.utils import merge_sections

if TYPE_CHECKING:
    from nomad.datamodel.datamodel import EntryArchive
    from structlog.stdlib import BoundLogger

m_package = SchemaPackage()


class OpticalMicroscopySettings(ArchiveSection):
    resolution = Quantity(
        type=int,
        description='Resolution of the resulting image in terms of pixels.',
        shape=[2],
        a_eln=ELNAnnotation(component=ELNComponentEnum.NumberEditQuantity),
    )
    magnification = Quantity(
        type=float,
        description='Magnification factor used for the resulting image.',
        a_eln=ELNAnnotation(component=ELNComponentEnum.NumberEditQuantity),
    )


class OpticalMicroscopyResults(MeasurementResult):
    image = Quantity(
        type=str,
        description='Image file generated by the microscope.',
        a_eln=ELNAnnotation(component=ELNComponentEnum.FileEditQuantity),
        a_browser=BrowserAnnotation(adaptor=BrowserAdaptors.RawFileAdaptor),
    )


class OpticalMicroscopy(Measurement, ElnParserSection):
    """
    An example ELN schema for optical microscopy measurements. Using `EntryData` as
    a parent section enables this section to be used for creating NOMAD entries.
    """

    m_def = Section(
        label='Optical Microscopy (Parser Tutorial 2)',
    )
    settings = SubSection(section_def=OpticalMicroscopySettings)
    results = SubSection(section_def=OpticalMicroscopyResults, repeats=True)

    def write_data(self, data_dict: dict, logger: 'BoundLogger') -> None:
        """
        Writes the data from the provided dictionary to the quantities of the schema.
        Uses the `merge_sections` utility function to merge the data coming from data
        file and that coming from the user's interaction with ELN quantities.

        Args:
            data_dict (dict): A dictionary containing the data to be written.
            logger (BoundLogger): A structlog logger.
        """
        measurement = OpticalMicroscopy()
        if datetime := data_dict.get('datetime'):
            measurement.datetime = datetime
        if (
            'sample' in data_dict
            and isinstance(data_dict['sample'], dict)
            and 'sample_ID' in data_dict['sample']
        ):
            measurement.m_setdefault('samples/0')
            measurement.samples[0].lab_id = data_dict['sample']['sample_ID']
            if 'description' in data_dict['sample']:
                measurement.description = data_dict['sample']['description']

        measurement.m_setdefault('settings')
        if resolution := data_dict.get('resolution'):
            measurement.settings.resolution = [float(x) for x in resolution.split('x')]
        if magnification := data_dict.get('magnification'):
            measurement.settings.magnification = float(magnification[:-1])

        measurement.m_setdefault('results/0')
        if image_file_name := data_dict.get('imageFileName'):
            measurement.results[0].image = os.path.join(
                os.path.dirname(self.data_file), image_file_name
            )

        merge_sections(self, measurement, logger=logger)

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        """
        Redefining the `normalize` method to read the data from the provided file and
        populate other quantities of the schema. This method is called when the entry
        is processed.
        """

        super().normalize(archive, logger)

        data_dict = {}
        if self.data_file is not None:
            data_dict = read_data_file(self.data_file, archive, logger)
        if data_dict:
            self.write_data(data_dict, logger)


m_package.__init_metainfo__()
