from nomad.datamodel.data import ArchiveSection, EntryData, Section
from nomad.datamodel.metainfo.annotations import (
    BrowserAdaptors,
    BrowserAnnotation,
    ELNAnnotation,
    ELNComponentEnum,
)
from nomad.datamodel.metainfo.basesections import Measurement, MeasurementResult
from nomad.metainfo import Quantity, SchemaPackage, SubSection

m_package = SchemaPackage()


class OpticalMicroscopySettings(ArchiveSection):
    resolution = Quantity(
        type=int,
        description='Resolution of the resulting image in terms of pixels.',
        shape=[2],
    )
    magnification = Quantity(
        type=float,
        description='Magnification factor used for the resulting image.',
    )


class OpticalMicroscopyResults(MeasurementResult):
    image = Quantity(
        type=str,
        description='Image file generated by the microscope.',
        a_eln=ELNAnnotation(component=ELNComponentEnum.FileEditQuantity),
        a_browser=BrowserAnnotation(adaptor=BrowserAdaptors.RawFileAdaptor),
    )


class OpticalMicroscopy(Measurement, EntryData):
    """
    An example schema for optical microscopy measurements.
    """

    m_def = Section(
        label='Optical Microscopy (Parser Tutorial 1)',
    )
    data_file = Quantity(
        type=str,
        description='Data file coming from the microscope.',
        a_eln=ELNAnnotation(component=ELNComponentEnum.FileEditQuantity),
        a_browser=BrowserAnnotation(adaptor=BrowserAdaptors.RawFileAdaptor),
    )
    settings = SubSection(section_def=OpticalMicroscopySettings)
    results = SubSection(section_def=OpticalMicroscopyResults, repeats=True)


m_package.__init_metainfo__()
